# Generated by Django 2.2.3 on 2019-07-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190717_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='image', upload_to='images/'),
        ),
    ]
