# Generated by Django 2.2.3 on 2019-07-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='appname',
            field=models.CharField(default='home', max_length=200),
        ),
    ]
